services:
  app:
    build: .
    ports:
      - "3005:3005"
    depends_on:
      - mongo
    networks:
      - proxy

  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root4Palestine
      - MONGO_INITDB_ROOT_PASSWORD=CinnaMon_1071.Qwerty
    volumes:
      - ./mongo-data:/data/db
    networks:
      - proxy
  #mongo-express:
  #  image: mongo-express:latest
  #  restart: always
  #  ports:
  #    - "8081:8081"
  #  environment:
  #    - ME_CONFIG_MONGODB_SERVER=mongo
  #    - ME_CONFIG_MONGODB_PORT=27017
  #    - ME_CONFIG_BASICAUTH_USERNAME=admin
  #    - ME_CONFIG_BASICAUTH_PASSWORD=pass
  #  depends_on:
  #    - mongo
  #  networks:
  #    - app-network
networks:
  proxy:
    external: true